packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
      babel-runtime: '*'
  gatsby-cli@*:
    dependencies:
      '@babel/runtime': '*'
  gatsby-core-utils@*:
    dependencies:
      '@babel/runtime': '*'
  react-scripts@*:
    dependencies:
      react-dom: "*"
      ts-pnp: "*"
  toasted-notes@*:
    dependencies:
      react-spring: "*"
  gatsby-theme-shopify-manager@*:
    dependencies:
      gatsby-source-shopify: "*"
      regenerator-runtime: "*"
  gatsby-plugin-apollo-shopify@*:
    dependencies:
      isomorphic-fetch: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'

yarnPath: .yarn/releases/yarn-berry.cjs
