yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      babel-runtime: "*"
      eslint-import-resolver-node: "*"
  gatsby-cli@*:
    dependencies:
      "@babel/runtime": "*"
  gatsby-core-utils@*:
    dependencies:
      "@babel/runtime": "*"
  gatsby-plugin-apollo-shopify@*:
    dependencies:
      isomorphic-fetch: "*"
  gatsby-theme-shopify-manager@*:
    dependencies:
      gatsby-source-shopify: "*"
      regenerator-runtime: "*"
  react-scripts@*:
    dependencies:
      react-dom: "*"
      ts-pnp: "*"
  toasted-notes@*:
    dependencies:
      react-spring: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

